// <auto-generated />
using LinkBoxWeb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LinkBoxWeb.Migrations
{
    [DbContext(typeof(LinkBoxContext))]
    [Migration("20180204005438_Added core data models")]
    partial class Addedcoredatamodels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LinkBoxWeb.DataModel.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int?>("TopicId");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("LinkBoxWeb.DataModel.Site", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("SiteId");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("LinkBoxWeb.DataModel.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int?>("SiteId");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("LinkBoxWeb.DataModel.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int?>("SubjectId");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("LinkBoxWeb.DataModel.Chapter", b =>
                {
                    b.HasOne("LinkBoxWeb.DataModel.Topic", "Topic")
                        .WithMany("Chapters")
                        .HasForeignKey("TopicId");
                });

            modelBuilder.Entity("LinkBoxWeb.DataModel.Subject", b =>
                {
                    b.HasOne("LinkBoxWeb.DataModel.Site", "Site")
                        .WithMany("Subjects")
                        .HasForeignKey("SiteId");
                });

            modelBuilder.Entity("LinkBoxWeb.DataModel.Topic", b =>
                {
                    b.HasOne("LinkBoxWeb.DataModel.Subject", "Subject")
                        .WithMany("Topics")
                        .HasForeignKey("SubjectId");
                });
#pragma warning restore 612, 618
        }
    }
}
